name: HogochiByebye
main: amata1219.hogochi.byebye.HogochiByebye
version: 1.0.0
depend: [WorldEdit,WorldGuard,FastAsyncWorldEdit,GriefPreventionX]
author: amata1219(Twitter@amata1219)

commands:
  rgview:
    description: debug command.
    usage: /<command>
    permission: hogochi.byebye.rgview
    permission-message: You do not have permission(<permission>).